version: '3'

services:
  quarkus-app:
    image: quarkus:latest
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://db:5433/db
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - rabbitmq-host=rabbitmq
      - rabbitmq-port=5672
      - rabbitmq-username=guest
      - rabbitmq-password=guest

    networks:
      - my_network
    depends_on:
      - db
      - rabbitmq
      - prometheus
      - grafana
      - elasticsearch
      - logstash
      - kibana

  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    container_name: db
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASSWORD=guest
    networks:
      - my_network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my_network


  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-configs:/etc/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - my_network

  elasticsearch:
    image: elasticsearch:7.16.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
      cluster.routing.allocation.disk.threshold_enabled: false
      xpack.security.enabled: false
    networks:
      - my_network

  logstash:
    image: logstash:7.16.1
    volumes:
      - ./config/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./config/logstash/pipelines/gelf.conf:/usr/share/logstash/config/pipelines/gelf.conf
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    networks:
      - my_network
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.16.1
    ports:
      - "5601:5601"
    environment:
      monitoring.ui.container.elasticsearch.enabled: true
      elasticsearch.hosts: "http://elasticsearch:9200"
    networks:
      - my_network

networks:
  my_network:
    external: true
    driver: host

volumes:
  grafana-data:
  grafana-configs: