version: '3'

services:
  quarkus-app:
    image: quarkus:latest
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://db:5432/db
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - rabbitmq-host=rabbitmq
      - rabbitmq-port=5672
      - rabbitmq-username=guest
      - rabbitmq-password=guest

    networks:
      - my_network
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: db
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASSWORD=guest
    networks:
      - my_network

networks:
  my_network:
    external: true
    driver: bridge